"""Mock-mode end-to-end agent tests.

These run without any LLM API key. Each agent must fall back to deterministic
local logic so the entire workflow remains exercisable offline.
"""

from __future__ import annotations

import time

from fastapi.testclient import TestClient


SAMPLE_MATERIAL = """
景德镇制瓷有上千年历史,起源于明代。
拉坯是重要工序,瓷土在转盘上成形,先粗坯,再修坯。
青花绘制使用毛笔,蘸青料在瓷胎上画纹样。
窑火烧制时,温度需控制在 1300 度以上。
工匠的双手在转盘上塑造瓷器,粉尘和泥水随处可见。
"""


def _wait(predicate, timeout=20.0, interval=0.1):
    deadline = time.time() + timeout
    while time.time() < deadline:
        if predicate():
            return True
        time.sleep(interval)
    return False


def test_full_pipeline_mock_mode_produces_real_artifacts():
    from server.data.models import FactCard, Shot, ShotAsset, Step
    from server.data.session import session_scope
    from server.main import create_app

    app = create_app()
    with TestClient(app) as client:
        project = client.post(
            "/api/projects",
            json={
                "title": "景德镇制瓷",
                "direction": "documentary",
                "brief": "非遗 15 镜验证 — 景德镇制瓷",
            },
        ).json()
        pid = project["id"]

        client.post(
            f"/api/projects/{pid}/materials",
            json={"content": SAMPLE_MATERIAL, "source_type": "text"},
        )

        run = client.post(
            "/api/runs",
            json={
                "project_id": pid,
                "workflow": "documentary_default",
                "auto_mode": True,
            },
        ).json()
        run_id = run["id"]

        def all_done():
            with session_scope() as session:
                steps = session.query(Step).filter(Step.graph_run_id == run_id).all()
                return steps and all(s.status == "success" for s in steps)

        assert _wait(all_done, timeout=30.0), "pipeline did not complete"

        # FactCards generated by research agent
        with session_scope() as session:
            facts = session.query(FactCard).filter(FactCard.project_id == pid).all()
            shots = session.query(Shot).filter(Shot.project_id == pid).all()
            assets = session.query(ShotAsset).filter(ShotAsset.project_id == pid).all()
        assert len(facts) >= 3, f"expected >=3 facts, got {len(facts)}"
        assert len(shots) == 15, f"expected exactly 15 shots, got {len(shots)}"

        jimeng_assets = [a for a in assets if a.asset_type == "jimeng_video_prompt"]
        assert len(jimeng_assets) >= 10, f"expected >=10 jimeng prompts, got {len(jimeng_assets)}"
        for ja in jimeng_assets[:3]:
            assert "纪录片" in ja.prompt or "观察式" in ja.prompt
            assert ja.rights["source_type"] == "ai_generated"
            assert ja.rights["review_status"] == "pending"

        # Step events: every agent must emit at least one artifact
        events = client.get(f"/api/runs/{run_id}/events").json()
        artifact_events = [e for e in events if e["event_type"] == "artifact"]
        agents_with_artifacts = {e["payload"].get("agent_name") for e in artifact_events}
        assert {"research", "writer", "storyboard", "review"} <= agents_with_artifacts


def test_research_agent_handles_empty_materials_gracefully():
    from server.main import create_app

    app = create_app()
    with TestClient(app) as client:
        project = client.post(
            "/api/projects", json={"title": "empty", "direction": "documentary"}
        ).json()
        run = client.post(
            "/api/runs",
            json={"project_id": project["id"], "workflow": "documentary_default", "auto_mode": True},
        ).json()

        def done():
            from server.data.models import Step
            from server.data.session import session_scope

            with session_scope() as session:
                steps = (
                    session.query(Step).filter(Step.graph_run_id == run["id"]).all()
                )
                if not steps:
                    return False
                statuses = [s.status for s in steps]
                return all(s in {"success", "failed"} for s in statuses)

        assert _wait(done, timeout=15.0)
        # First step should succeed even with empty materials (warning + finish)
        run_after = client.get(f"/api/runs/{run['id']}").json()
        assert run_after["steps"][0]["status"] == "success"
